services:
  - type: web
    name: trestle-rag-assignment
    env: python
    pythonVersion: 3.11.4
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT